trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- script: |
    echo "Checking Azure CLI version"
    az version
  displayName: 'Check Azure CLI'

- script: |
    echo "Checking Bicep version"
    az bicep version
  displayName: 'Check Bicep CLI'

- script: |
    echo "Building Bicep template"
    az bicep build --file infra/main.bicep
  displayName: 'Build Bicep template'

- script: |
    echo "Listing infra folder"
    ls infra
  displayName: 'Verify compiled template'